# Generated by Django 3.1.4 on 2021-05-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='targets',
            fields=[
                ('target_id', models.IntegerField(primary_key=True, serialize=False)),
                ('route_id', models.IntegerField()),
                ('item_code', models.CharField(max_length=25)),
                ('item_description', models.CharField(max_length=150)),
                ('TARGET_MONTH', models.CharField(choices=[('JAN', 'January'), ('FEB', 'FEBRUARY'), ('MAR', 'MARCH'), ('APR', 'APRIL'), ('MAY', 'MAY'), ('JUN', 'JUNE'), ('JUL', 'JULY'), ('AUG', 'AUGUST'), ('SEPT', 'SEPTEMBER'), ('OCT', 'OCTOBER'), ('NOV', 'NOVEMEBER'), ('DEC', 'DECEMBER')], default='JAN', max_length=5)),
                ('WORKINGDAYS', models.IntegerField(default=26)),
            ],
        ),
    ]
