# Generated by Django 3.1.4 on 2021-05-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('client_code', models.IntegerField(primary_key=True, serialize=False)),
                ('client_description', models.CharField(max_length=150)),
                ('region_code', models.CharField(default='DXB', max_length=3)),
                ('city_code', models.CharField(max_length=3)),
                ('subchannel', models.CharField(max_length=15)),
                ('channel', models.CharField(max_length=15)),
                ('Area_of_business', models.CharField(max_length=3)),
                ('address', models.TextField()),
                ('alt_address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
